before:
  hooks:
    - make tidy
  
builds:
  - id: registry
    dir: cmd/registry
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/jsirianni/registry/version.version=v{{ .Version }}
      - -X github.com/jsirianni/registry/version.gitHash={{ .FullCommit }}
      - -X github.com/jsirianni/registry/version.date={{ .Date }}
    no_unique_dist_dir: false

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - id: registry
    file_name_template: "{{ .PackageName }}_{{ .Os }}_{{ .Arch }}"
    maintainer: github.com/jsirianni
    package_name: registry
    homepage: https://github.com/jsirianni/registry
    license: Apache 2.0
    formats:
      - rpm
      - deb
      - apk

dockers:
  - goos: linux
    goarch: amd64
    ids:
      - registry
    image_templates:
      - "ghcr.io/jsirianni/registry-amd64:latest"
      - "ghcr.io/jsirianni/registry-amd64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "ghcr.io/jsirianni/registry-amd64:{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/jsirianni/registry-amd64:{{ .Major }}"
      - "ghcr.io/jsirianni/registry-amd64:{{ .ShortCommit }}"
    dockerfile: ./Dockerfile
    use: buildx
    build_flag_templates:
      - "--label=created={{.Date}}"
      - "--label=title={{.ProjectName}}"
      - "--label=revision={{.FullCommit}}"
      - "--label=version={{.Version}}"
  - goos: linux
    goarch: arm64
    ids:
      - registry
    image_templates:
      - "ghcr.io/jsirianni/registry-arm64:latest"
      - "ghcr.io/jsirianni/registry-arm64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "ghcr.io/jsirianni/registry-arm64:{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/jsirianni/registry-arm64:{{ .Major }}"
      - "ghcr.io/jsirianni/registry-arm64:{{ .ShortCommit }}"
    dockerfile: ./Dockerfile
    use: buildx
    build_flag_templates:
      - "--label=created={{.Date}}"
      - "--label=title={{.ProjectName}}"
      - "--label=revision={{.FullCommit}}"
      - "--label=version={{.Version}}"

docker_manifests:
  - name_template: "ghcr.io/jsirianni/registry:latest"
    image_templates:
      - "ghcr.io/jsirianni/registry-amd64:latest"
      - "ghcr.io/jsirianni/registry-arm64:latest"
    skip_push: false
  - name_template: "ghcr.io/jsirianni/registry:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    image_templates:
      - "ghcr.io/jsirianni/registry-amd64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "ghcr.io/jsirianni/registry-arm64:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    skip_push: false
  - name_template: "ghcr.io/jsirianni/registry:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/jsirianni/registry-amd64:{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/jsirianni/registry-arm64:{{ .Major }}.{{ .Minor }}"
    skip_push: false
  - name_template: "ghcr.io/jsirianni/registry:{{ .Major }}"
    image_templates:
      - "ghcr.io/jsirianni/registry-amd64:{{ .Major }}"
      - "ghcr.io/jsirianni/registry-arm64:{{ .Major }}"
    skip_push: false
  - name_template: "ghcr.io/jsirianni/registry:{{ .ShortCommit }}"
    image_templates:
      - "ghcr.io/jsirianni/registry-amd64:{{ .ShortCommit }}"
      - "ghcr.io/jsirianni/registry-arm64:{{ .ShortCommit }}"

checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}-SHA256SUMS"
  algorithm: sha256

release:
  draft: false

changelog:
  skip: false
  use: github
  sort: asc
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: "Dependencies"
      regexp: "^.*deps[(\\w)]*:+.*$"
      order: 30
    - title: Other
      order: 999
