name: check-formatting
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check-fmt:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.18"
          check-latest: true
        
      - name: Check Formatting
        run: make check-fmt
