name: misspell
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  misspell:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.18"
          check-latest: true

      - name: Install Misspell
        run: go install github.com/client9/misspell/cmd/misspell@v0.3.4
        
      - name: Check for Misspelled Words in Doc Files
        run: make misspell
