name: release
on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io

jobs:
  goreleaser:
    runs-on: ubuntu-20.04
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.18"

      - name: Cache Go Modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-20.04
    needs: goreleaser
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Gcloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Install kubectl
        run: gcloud components install kubectl

      - name: Install Gomplate
        run: |
          wget https://github.com/hairyhenderson/gomplate/releases/download/v3.9.0/gomplate_linux-amd64-slim
          chmod +x gomplate_linux-amd64-slim && mv gomplate_linux-amd64-slim gomplate

      - name: Deploy
        run: |
          gcloud container clusters get-credentials $CLUSTER_NAME \
            --zone $CLUSTER_ZONE \
            --project $GCP_PROJECT

          TAG="${REF:1}"
          export IMAGE_TAG="${IMAGE}:${SHA}"
          ./gomplate --file deploy/k8s/deployment.gotmpl | kubectl apply -f -
        env:
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
          CLUSTER_ZONE: ${{ secrets.CLUSTER_ZONE }}
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          NAMESPACE: ${{ secrets.NAMESPACE }}
          IMAGE: ghcr.io/jsirianni/registry
          INGRESS_CLUSTER_ISSUER: ${{ secrets.INGRESS_CLUSTER_ISSUER }}
          INGRESS_HOSTNAME: ${{ secrets.INGRESS_HOSTNAME }}
          REF: ${{ github.ref_name }}
